---
- name: to uninstall httpd service
  hosts: all
  become: true
  tasks:
  - name: to stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RHEL"

  - name: to uninstall httpd package
    yum: 
      name: httpd
      state: absent
    when: ansible_os_family == "RHEL"

